import type { Qc1Category, QuoteProduct } from "@/types/quotes";

/** QC1 column A categories — PV Quote.xlsx */
export const SOLAR_QC1_CATEGORIES: Qc1Category[] = [
  { id: "solar-pv-panels", label: "PV PANELS", templateId: "solar_pv_v1" },
  { id: "solar-mounting", label: "MOUNTING", templateId: "solar_pv_v1" },
  { id: "solar-inverters", label: "INVERTERS", templateId: "solar_pv_v1" },
  { id: "solar-batteries", label: "BATTERIES", templateId: "solar_pv_v1" },
  { id: "solar-accessories", label: "ACCESSORIES", templateId: "solar_pv_v1" },
];

export const SOLAR_QC1_PRODUCTS: QuoteProduct[] = [
  {
    id: "panel-ja-700",
    templateId: "solar_pv_v1",
    categoryId: "solar-pv-panels",
    partCode: "JA-700",
    name: "JA Solar 700W (144-cell, bifacial)",
    comment: "Mono Perc, glass-on-glass",
    listPrice: 1714.44,
    wattsPerPanel: 700,
    tags: [],
  },
  {
    id: "panel-canadian-580",
    templateId: "solar_pv_v1",
    categoryId: "solar-pv-panels",
    partCode: "CS-580",
    name: "Canadian Solar 580W",
    listPrice: 1390.24,
    wattsPerPanel: 580,
    tags: [],
  },
  {
    id: "panel-aiko-605",
    templateId: "solar_pv_v1",
    categoryId: "solar-pv-panels",
    partCode: "AIKO-605",
    name: "Aiko 605W",
    listPrice: 1333.89,
    wattsPerPanel: 605,
    tags: [],
  },
  {
    id: "mount-flat-concrete",
    templateId: "solar_pv_v1",
    categoryId: "solar-mounting",
    name: "Brackets — flat roof, concrete fixed tilt",
    listPrice: 800,
    unitLabel: "per panel",
    tags: [],
  },
  {
    id: "mount-pitched-ibr",
    templateId: "solar_pv_v1",
    categoryId: "solar-mounting",
    name: "Brackets — pitched roof, steel IBR",
    listPrice: 500,
    unitLabel: "per panel",
    tags: [],
  },
  {
    id: "inv-fox-5k-1ph",
    templateId: "solar_pv_v1",
    categoryId: "solar-inverters",
    name: "Fox H-Series 5kW hybrid (single phase)",
    listPrice: 13879.75,
    kwRating: 5,
    tags: ["single-phase", "fox", "hybrid", "high-voltage"],
  },
  {
    id: "inv-fox-10k-1ph",
    templateId: "solar_pv_v1",
    categoryId: "solar-inverters",
    name: "Fox K-Series 10.5kW hybrid (single phase)",
    listPrice: 24560.76,
    kwRating: 10.5,
    tags: ["single-phase", "fox", "hybrid", "high-voltage"],
  },
  {
    id: "inv-fox-30k-3ph",
    templateId: "solar_pv_v1",
    categoryId: "solar-inverters",
    name: "Fox 30kW hybrid (3-phase)",
    listPrice: 49215.88,
    kwRating: 30,
    tags: ["three-phase", "fox", "hybrid", "high-voltage"],
    defaultQty: 1,
  },
  {
    id: "inv-deye-12k-3ph",
    templateId: "solar_pv_v1",
    categoryId: "solar-inverters",
    name: "Deye 12kW hybrid (3-phase)",
    listPrice: 32914.18,
    kwRating: 12,
    tags: ["three-phase", "deye", "hybrid", "low-voltage"],
  },
  {
    id: "inv-sunsynk-16k-1ph",
    templateId: "solar_pv_v1",
    categoryId: "solar-inverters",
    name: "Sunsynk 16kW hybrid (single phase)",
    listPrice: 47884.18,
    kwRating: 16,
    tags: ["single-phase", "sunsynk", "hybrid", "low-voltage"],
  },
  {
    id: "bat-fox-10k-hv",
    templateId: "solar_pv_v1",
    categoryId: "solar-batteries",
    name: "Fox 10.4kWh HV (1C, 90% DOD)",
    listPrice: 29811.31,
    kwhPerUnit: 10.4,
    tags: ["fox", "high-voltage", "hybrid"],
  },
  {
    id: "bat-fox-5k-hv",
    templateId: "solar_pv_v1",
    categoryId: "solar-batteries",
    name: "Fox 5.2kWh HV (1C, 90% DOD)",
    listPrice: 17788.5,
    kwhPerUnit: 5.2,
    tags: ["fox", "high-voltage", "hybrid"],
  },
  {
    id: "bat-deye-5k-lv",
    templateId: "solar_pv_v1",
    categoryId: "solar-batteries",
    name: "Deye 5.12kWh LV (1C, 90% DOD, excl. BMS)",
    listPrice: 14500,
    kwhPerUnit: 5.12,
    tags: ["deye", "low-voltage", "hybrid"],
  },
  {
    id: "bat-sunsynk-10k",
    templateId: "solar_pv_v1",
    categoryId: "solar-batteries",
    name: "Sunsynk 10.65kWh (1C, 95% DOD, incl. BMS)",
    listPrice: 35280,
    kwhPerUnit: 10.65,
    tags: ["sunsynk", "low-voltage", "hybrid"],
  },
  {
    id: "acc-battery-fuse",
    templateId: "solar_pv_v1",
    categoryId: "solar-accessories",
    name: "Battery fuse holder",
    listPrice: 950,
    tags: [],
  },
  {
    id: "acc-smart-logger-30k",
    templateId: "solar_pv_v1",
    categoryId: "solar-accessories",
    name: "Smart logger — 30kW parallel",
    listPrice: 3021.75,
    tags: ["fox", "three-phase"],
  },
];
